### ISSUE TITLE
Warning:Failed to write to content log:Bad file descriptor

### ISSUE THREAD

**Issue by istipovic** [droe/sslsplit#122]
Hi , 
I just installed sslsplit and all seems to work fine except it does not write log files.

sslsplit -D -l connections.log -j /tmp/sslsplit -S /tmp/sslsplit/logdir -k sslsplit.key -c sslsplit.crt ssl 0.0.0.0 8443 tcp 0.0.0.0 8080

I tried to create the /tmp/sslsplit and /tmp/sslsplit/logir manually, even gave it 777 permission, checked /var/logs... but cannot determine the reason why it is not able to write anything.

The folder is empty- no single file written.

First error message is Failed to open /tmp/sslsplit/logdir/2016xxxxx....." : No such file or directory

After that comes "Warning :Failed to write to content log: Bad file descriptor".

uname -a:
Linux kali 4.0.0-kali1-686-pae #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) i686 GNU/Linux
sslsplit -v:
SSLsplit (built 2014-05-26)

Thanks in advance

**Comment by droe** [comment]
That's not the output of `sslsplit -V`, can you provide the actual output so I can see exactly what codebase are you running? Quite likely you should try the master branch, the log file handling has been revamped to play well with chrooting and dropping privs, some of which was done automatically in previous releases.

**Comment by istipovic** [comment]
Hi, 

I resolved the issue in the meanwhile - it was required to create the "logdir" folder manually.

sslsplit -V is as follows (on Kali -even though it is outdated somewhat it still works ok once the manual folder is created):

SSLsplit  (built 2014-05-26)
Copyright (c) 2009-2014, Daniel Roethlisberger <daniel@roe.ch>
http://www.roe.ch/SSLsplit
Features: -DDISABLE_SSLV2_SESSION_CACHE -DHAVE_NETFILTER
NAT engines: netfilter* tproxy
netfilter:  IP_TRANSPARENT SOL_IPV6 !IPV6_ORIGINAL_DST
compiled against OpenSSL 1.0.1e 11 Feb 2013 (1000105f)
rtlinked against OpenSSL 1.0.1k 8 Jan 2015 (100010bf)
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
Using SSL_MODE_RELEASE_BUFFERS
Using direct access workaround when loading certs
SSL/TLS algorithm availability: RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
compiled against libevent 2.0.19-stable
rtlinked against libevent 2.0.21-stable
1 CPU cores detected

Thanks

Regards

**Comment by droe** [comment]
Something is wrong in that Kali build in that it does not show the Git revision hash in `-V`. But in any case, this should be resolved in latest develop. Closing issue.

**Comment by StevePham88** [comment]
Im getting the same issue, can not log connection to files. I also manually mkdir /tmp/sslsplit/logidr but no luck:
![image](https://user-images.githubusercontent.com/19483861/35799299-d195a27e-0a97-11e8-8109-73d940eb40f6.png)

![image](https://user-images.githubusercontent.com/19483861/35799271-bba58d80-0a97-11e8-9968-a2dcefa08f3a.png)

**Comment by droe** [comment]
Please upgrade to the latest release, sslsplit 0.4.7 is ancient (over 4.5 years old). Chances are that this was fixed a long time ago.

**Comment by StevePham88** [comment]
Hi,
I have upgrade the lastest version 0.5.1 but still no luck

![image](https://user-images.githubusercontent.com/19483861/35841224-846d07bc-0b2d-11e8-9704-63dfbf60f378.png)
![image](https://user-images.githubusercontent.com/19483861/35841235-8cdb5976-0b2d-11e8-89fc-393174c3f035.png)
![image](https://user-images.githubusercontent.com/19483861/35841252-9d6bc654-0b2d-11e8-9347-22272987b78b.png)
![image](https://user-images.githubusercontent.com/19483861/35841260-a69a2f72-0b2d-11e8-8fac-3569559b8f9b.png)

**Comment by droe** [comment]
There was no successful connection, ergo nothing to log.
This is unrelated to this issue ticket, please open a new issue if you believe to have found a bug.
